### ISSUE TITLE
need additional  error handling for missing Toolcontroller/tool pproperties.

### ISSUE THREAD

**Issue by spanner888** [dubstar-04/FeedsAndSpeeds#14]
Opened a test document I created late 2020 & FS calc output:

18:43:32  Traceback (most recent call last):
  File "C:/Users/spanner888/AppData/Roaming/FreeCAD/Macro/FS_open.FCMacro", line 3, in <module>
    PathFeedsAndSpeedsGui.Show()
  File "C:\Users\spanner888\AppData\Roaming\FreeCAD\Mod\fsMaster\PathFeedsAndSpeedsGui.py", line 186, in Show
    panel = FeedSpeedPanel()
  File "C:\Users\spanner888\AppData\Roaming\FreeCAD\Mod\fsMaster\PathFeedsAndSpeedsGui.py", line 24, in __init__
    self.setup_ui()
  File "C:\Users\spanner888\AppData\Roaming\FreeCAD\Mod\fsMaster\PathFeedsAndSpeedsGui.py", line 57, in setup_ui
    self.load_tool_properties()
  File "C:\Users\spanner888\AppData\Roaming\FreeCAD\Mod\fsMaster\PathFeedsAndSpeedsGui.py", line 97, in load_tool_properties
    flutes = tool.Flutes
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'Flutes'

I have a vague memory that this may have been a late addition in new ToolBits system. Regardless other users may run into this as well.

**Comment by spanner888** [comment]
confirmed in forum by user "phil from seattle" in FC forum post https://forum.freecadweb.org/viewtopic.php?f=15&t=59856&start=30#p521114

Hopefully I will have some time to look at this & other issues in ~10 days, but was also hoping from some suggested approach from @dubstar-04 on how to approach this.
